i = input('Digite algo: ')
print('{} é de qual tipo? {}'.format(i, type(i)))
print('{} é numérico? {}'.format(i, i.isnumeric()))
print('{} é alfabético? {}'.format(i, i.isalpha()))
print('{} é alfanumérico? {}'.format(i, i.isalnum()))
print('{} é ASCII? {}'.format(i, i.isascii()))
print('{} é decimal? {}'.format(i, i.isdecimal()))
print('{} é dígito? {}'.format(i, i.isdigit()))
print('{} é identificador? {}'.format(i, i.isidentifier()))
print('{} é escrito em minúsculas? {}'.format(i, i.islower()))
print('{} pode ser impresso? {}'.format(i, i.isprintable()))
print('{} é um espaço? {}'.format(i, i.isspace()))
print('{} é um título? {}'.format(i, i.istitle()))#ou seja, tem a 1a letra maiúscula?
print('{} é escrito em maiúsculas? {}'.format(i, i.isupper()))
print(f'{i} é escrito em minúsculas? {i.isupper()}')
